name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t weather-app:latest .

    - name: Run container in detached mode
      run: docker run -d --name weather-test -p 5000:5000 weather-app:latest

    - name: Wait for container to be healthy
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5000 | grep "Weather App"; then
            echo "App is responding"
            exit 0
          else
            echo "Waiting for app to respond..."
            sleep 3
          fi
        done
        echo "App did not respond in time"
        exit 1

   # - name: Stop and remove container
    #  run: docker rm -f weather-test

    # Optional: Push to GitHub Container Registry
    # Uncomment if you want to push the image
    - name: Tag image
      run: docker tag weather-app:latest ghcr.io/${{ github.repository_owner }}/weather-app:latest

    - name: Push image
      run: docker push ghcr.io/${{ github.repository_owner }}/weather-app:latest
